import numpy as np

NUM_WEEKDAY = 7
MAX_PREDICT_TIMESTAMP = 90 * 24 * 60 * 60
PREDICT_BUCKET_INTERVAL = 24 * 60 * 60

NUM_CLASS = MAX_PREDICT_TIMESTAMP // PREDICT_BUCKET_INTERVAL + 1

MAX_LOOKBACK_DAYS = 90
MAX_LOOKBACK_TIMESTAMP = MAX_LOOKBACK_DAYS * 24 * 60 * 60

MAX_HISTORY_NUM_TRIPLET = 64
MAX_HISTORY_NUM_PAIR = 64
MAX_HISTORY_NUM_NODE = 64

NUM_EDGE_TYPE = 248

SECONDS_PER_DAY = 24 * 60 * 60
SECONDS_PER_HOUR = 60 * 60

MAX_TE_DAYS_DIFF = 800
MAX_TE_HOURS_DIFF = 5000

MAX_DIRECTION_VALUE = 3
NUM_HOUR = 24

TE_FEAT_DIM = np.array([MAX_TE_DAYS_DIFF, MAX_TE_HOURS_DIFF,
                        NUM_WEEKDAY, NUM_HOUR, MAX_DIRECTION_VALUE])

TE_FEAT_EMB_NUM = np.sum(TE_FEAT_DIM, dtype='int64')

EDGE_TYPE_FEAT_DIM = np.array([247, 19, 142]) + 2

NODE_FEAT_DIM = np.array([32, 22, 15, 416, 62, 223, 19, 27]) + 2

EDGE_TYPE_FEAT_EMB_NUM = np.sum(EDGE_TYPE_FEAT_DIM)
NODE_FEAT_EMB_NUM = np.sum(NODE_FEAT_DIM)

EDGE_FEAT_DIM = np.concatenate((NODE_FEAT_DIM, NODE_FEAT_DIM, EDGE_TYPE_FEAT_DIM))
EDGE_FEAT_EMB_NUM = NODE_FEAT_EMB_NUM * 2 + EDGE_TYPE_FEAT_EMB_NUM

LABEL_FEAT_DIM = np.array([NUM_CLASS, NUM_WEEKDAY])
LABEL_FEAT_EMB_NUM = np.sum(LABEL_FEAT_DIM)

PACK_FILE_SIZE = 100

PAIR_FEAT_DIM = np.concatenate((TE_FEAT_DIM, EDGE_TYPE_FEAT_DIM, [2]))
PAIR_FEAT_EMB_NUM = np.sum(PAIR_FEAT_DIM)
